### ISSUE TITLE
* ~plugins/axios in ./middleware/ssr-cookie.js

### ISSUE THREAD

**Issue by se7en-1992** [nuxt-community/express-template#100]
error:
![4c2ba1f0-a4f5-479d-bcfe-c327246837e0](https://user-images.githubusercontent.com/19768530/35847354-2df3f260-0b55-11e8-8fbb-e1fa34b75bb4.png)

middleware/ssr-cookie.js:
``` js
import axios from '~plugins/axios'

export default function({isServer, req}) {
  if (isServer) {
    axios.defaults.headers.common.cookie = req.headers.cookie
  }
}
```

plugins/axios.js
``` js
import * as axios from 'axios'

let options = {}
// The server-side needs a full url to works
if (process.server) {
  options.baseURL = `http://${process.env.HOST || 'localhost'}:${process.env.PORT || 3000}`
}

export default axios.create(options)

```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c79">#c79</a>)</em></sub></div>

**Comment by Prozi** [comment]
replace `~plugins` with `~/plugins`
