### ISSUE TITLE
Cannot resolve symbols Nuxt and Builder imported from nuxt

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/express-template#102]
I'm using Webstorm for my development. Once I've imported Nuxt and Builder from 'nuxt' I'm getting a warning that Webstorm can't resolve those symbols. I also don't get any autocompletion for those items. 
![image](https://user-images.githubusercontent.com/2766448/37520144-f8f72be0-292c-11e8-9ebc-5600ac2317dc.png)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c81">#c81</a>)</em></sub></div>

**Comment by Revel109** [comment]
Use VsCode Instead. Btw, why you need to import Nuxt in this way?

**Comment by AndrewBogdanovTSS** [comment]
@Revel109 it's great that you didn't recommend to use Angular to me instead of Nuxt and Vue. Why do I need to import Nuxt? Have you ever write a Nuxt-Express app before? I guess you didn't

**Comment by Revel109** [comment]
@AndrewBogdanovTSS  Yes, i didn't write it before. But i did work with nuxt for almost 1 year. I didn't import nuxt like in this way ever. That's why i did ask to you.

**Comment by AndrewBogdanovTSS** [comment]
@Revel109 I suppose you've been using Nuxt with no built in back-end, in order to use Nuxt with Express you **have to** import it like that since it's no longer managed by a simple initialization process that is built into Nuxt

**Comment by Revel109** [comment]
@AndrewBogdanovTSS Got it now. But this issue haven't solved yet?
You could manage it by your own way?

**Comment by AndrewBogdanovTSS** [comment]
If it was solved I would've closed it. If I could've managed it by myself I wouldn't create an issue in the first place
