### ISSUE TITLE
Switch to express

### ISSUE THREAD

**Issue by kossa** [nuxt-community/express-template#105]
Hello,

I used nuxt-community/starter-template once I finished my project, I want to use express, there is way to switch directly ? or to run my code on express ?

Thank you

**Comment by hartmut-co-uk** [comment]
Hi, @kossa have a look at https://github.com/nuxt-community/express-template

**Comment by kossa** [comment]
The project already exist, i’ll not start a new project!!

**Comment by hartmut-co-uk** [comment]
sure, but you can still check out how to setup express as your server.. just as a starting point if you're still interested...
https://github.com/nuxt-community/express-template/blob/master/template/server/index.js

**Comment by kossa** [comment]
More clear, Thank you for help :D
