### ISSUE TITLE
hot reloading not work

### ISSUE THREAD

**Issue by mamtou** [nuxt-community/express-template#119]
rt, when I excute "npm install", and run dev, It's show

![image](https://user-images.githubusercontent.com/2018519/41398094-c669dc56-6fe8-11e8-898b-d7d8338a074e.png)

But when I change some data, hot reloading not work

**Comment by gaetansenn** [comment]
Hello @mamtou 

Which kind of data did you changed ? a .vue file .css file ... ?

**Comment by mamtou** [comment]
background data file (./api/routes/users.js)

**Comment by gamelaster** [comment]
@mamtou for this you must restart the server. Or use this awesome express module:
https://github.com/uptownhr/nuxt-express-module

**Comment by mamtou** [comment]
I had fixed it by nodemon, thank you guys

**Comment by SixBytesUnder** [comment]
Hi @mamtou 
Can you please share how you fixed it with nodemon?
I have the same issue, and running `nodemon api\index.js` doesn't seem to help.

**Comment by gamelaster** [comment]
@SixBytesUnder 
Hello, for hot-reloading I recommend to use 
https://github.com/uptownhr/nuxt-express-module .

**Comment by mamtou** [comment]
@SixBytesUnder  nodemon --watch api --exec  “nuxt”
