### ISSUE TITLE
Cannot resolve '@' as nuxt does in regular nuxt project

### ISSUE THREAD

**Issue by payalord** [nuxt-community/express-template#173]
Starting from file `api/index.js`, where express server begins and nuxt serverMiddleware setup, all import paths with '@' cannot find that path/files to import. Here are the error in console:
```
ERROR  Cannot find module '@/api/routes/users'
```
What I need is for '@' to point to project root dir so i can include my custom js files from there, from any file that will be used in this server middleware including itself. My code of `api/index.js`:

```
import express from 'express'
import users from '@/api/routes/users'

const app = express()

// Import API Routes
app.use(users)

// Export the server middleware
module.exports = {
  path: '/api',
  handler: app
}
```

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/express-template/issues/c122">#c122</a>)</em></sub></div>

**Comment by Prozi** [comment]
you need either tsconfig or webpack config for resolving @ alias to another path

**Comment by Prozi** [comment]
@payalord

**Comment by payalord** [comment]
@Prozi thanks for trying to help me, we discussed this here in [nuxt issues thread](https://github.com/nuxt/nuxt.js/issues/7017#issuecomment-597473117). And I provided my solution there.
