### ISSUE TITLE
How can I use absolute import in express api backend?

### ISSUE THREAD

**Issue by ZombieChibiXD** [nuxt-community/express-template#196]
In nuxt .vue files, I can just use '@/path/to/component', but for some reason the same thing don't work on the express.js files..

**Comment by SWDevStudio** [comment]
I have the same problem, I can not understand how to set up the work of alias for Express files

**Comment by kotvasili** [comment]
```
import moduleAlias from "module-alias";

moduleAlias.addAliases({
  "@": path.join(__dirname, "/../"),
});

@ZombieChibiXD This is how I solved it inside serverMiddleware folder
