### ISSUE TITLE
How to use express-session with new serverMiddleware approach?

### ISSUE THREAD

**Issue by SnitchRUS66** [nuxt-community/express-template#198]
How to use express-session with new serverMiddleware approach? When I call req.session in nuxtServerInit it is undefined.

**Comment by SnitchRUS66** [comment]
Yes, that's what I did. After 6 hours of experimenting, I came up with success. If register middleware as
```
serverMiddleware: {
    '/api': '~/index'
},
```
It turns out that the `req.session` is undefined in nuxtServerInit.
But if register middleware as
```
serverMiddleware: [
    '~/index'
],
```
It starts work correctly. Maybe I misunderstand something? This issue also related to https://github.com/nuxt/nuxt.js/issues/5119

**Comment by Coinhexa** [comment]
What happens if nuxt is on the frontend at localhost:3000 and express is a separate backend at localhost:8000 with express-session, how does it work there

**Comment by yfliao90** [comment]
> Yes, that's what I did. After 6 hours of experimenting, I came up with success. If register middleware as
> 
> ```
> serverMiddleware: {
>     '/api': '~/index'
> },
> ```
> 
> It turns out that the `req.session` is undefined in nuxtServerInit. But if register middleware as
> 
> ```
> serverMiddleware: [
>     '~/index'
> ],
> ```
> 
> It starts work correctly. Maybe I misunderstand something? This issue also related to [nuxt/nuxt#5119](https://github.com/nuxt/nuxt/issues/5119)

Thanks to your answer I finally struggled out my problem.

I guess 

`serverMiddleware: [
    '~/index'
],`

means

`serverMiddleware: [
    { path : '/', handler: '~/index'}
],`

Only if this express-session server middleware applied to whole routes will it work.
