### ISSUE TITLE
New install with the cli, app not in dev mode?

### ISSUE THREAD

**Issue by Camzilla** [nuxt-community/express-template#23]
I think I created an issue ticket on the wrong project before (https://github.com/nuxt/koa/issues/8), made sure to try this template with a clean cli install, but it didn't help. Tried logging the config in app.js but dev is always false, something missing or is it me this time too? 😔

**Comment by Atinux** [comment]
Can you check if you don't have NODE_ENV set to `production` in your environnement variables @Camzilla ?

You can list them by launching this command in your terminal:
```bash
env
```

**Comment by Camzilla** [comment]
Does your command work in a mac terminal only? Hmm I don't think it's in my global env variables at least:

![image](https://cloud.githubusercontent.com/assets/7138189/25424154/a19b7f46-2a67-11e7-94c9-f83c9285acbb.png)

**Comment by Atinux** [comment]
Can you try a fresh install and test if the dev mode works now?

**Comment by Camzilla** [comment]
I did and get an error upon running `npm run dev`: "Error: Cannot find module C:DevExperimentdevenvtestegister.js'source-map-support" seems like the "/" has fallen out.
