### ISSUE TITLE
How to use nuxt on production?

### ISSUE THREAD

**Issue by fortil** [nuxt-community/express-template#36]
Hi guys

I need to show my nuxt server in a middleware, but you show the  `nuxt.build` in this page [L25](https://github.com/nuxt/express/blob/master/template/server/index.js#L25) in the development enviroment. However I need an example of nuxt in a production enviroment. 
Can somebody help me?

**Comment by fortil** [comment]
Do somebody has an idea?
I can't deploy my first app with Nuxt in EC2 AWS. :'( , Also I hope to help give you docs Sails.js - Nuxt

**Comment by BEaStia** [comment]
@fortil How do you deploy it?

**Comment by fortil** [comment]
Hi @BEaStia
I'm building my first project with Nuxt and Sails.JS, the first one I use it as middleware and the second one as REST API.

Sails.js its build with express, so it haves a middleware options in a var named [http](https://sailsjs.com/documentation/reference/configuration/sails-config-http), here I put the code as its shown in the guide of nuxt-express (previous version because current alpha version doesn't work to me).
```
 customMiddleware: function (app) {
    const Nuxt = require('nuxt')
    let config = require('../nuxt.config.js')
    const express = require('express')

    const nuxt = new Nuxt(config)
    config.dev = !(process.env.NODE_ENV === 'production')
    app.use(nuxt.render)
    if (config.dev) {
      nuxt.build()
      .catch((error) => {
        console.error(error)
        process.exit(1)
      })
    }
  }
```
I try to build Nuxt (`nuxt build`) and next I try to put some codes, as this:
```
customMiddleware: function (app) {
    const Nuxt = require('nuxt')
    let config = require('../nuxt.config.js')
    const express = require('express')

    const nuxt = new Nuxt(config)
    config.dev = !(process.env.NODE_ENV === 'production')
    app.use(nuxt.render)
    if (config.dev) {
      nuxt.build()
      .catch((error) => {
        console.error(error)
        process.exit(1)
      })
    } else {
      app.use('/', express.static('../dist/index.html'))
    }
  }
```
But doesn't work, it does not show error, the page only keep loading.

Thanks

**Comment by fortil** [comment]
Hi

Again me, I can use `cross-env NODE_ENV=production node server.js` and works it, but I need use it with foreverjs.

I run `sudo forever start -ae errors.log server.js --prod --port 80` or `sudo forever start -ae errors.log server.js --prod --port 3000`, doesn't work to me.

_server.js_ has:
```
const Nuxt = require('nuxt')
const app = require('express')()
const port = process.env.PORT || 3000

// We instantiate Nuxt.js with the options
let config = require('./nuxt.config.js')
const nuxt = new Nuxt(config)
app.use(nuxt.render)
// Build only in dev mode
if (config.dev) {
  nuxt.build()
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
}
// Listen the server
app.listen(port, '0.0.0.0')
console.log('Server listening on localhost:' + port)
```
When I to run `npm start` (`cross-env NODE_ENV=production node server.js`)` it is works but with foreverjs not.

**Comment by Atinux** [comment]
Hi @fortil 

This should work: `NODE_ENV=production sudo forever start -ae errors.log server.js --port 80`

**Comment by fortil** [comment]
Thanks @Atinux !!
I will try
