### ISSUE TITLE
Error when init the project

### ISSUE THREAD

**Issue by DavidBernal** [nuxt-community/express-template#45]
Hello,

I have this error just create project:

`(node:180) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: app.use() requires middleware functions`

Steps: 
 - vue init nuxt/express project-name
 - yarn
 - npm run dev

NODE_ENV variable is undefined. 
Nuxt is installed globally.

The machine is Windows 10.
I try with node 6.9.5 and 8.0.0 and get same error.

**Comment by 1002237913** [comment]
@DavidBernal : yarn upgrade nuxt

**Comment by SoullessWaffle** [comment]
@DavidBernal could you reopen this issue? The template should probably be updated to fix this.

**Comment by uptownhr** [comment]
all, i'm getting the same issue and I ran yarn upgrade to address the unahndled error. However, even after, the server does not respond. It is as if the express.render does nothing. The browser just sits and waits. I also do not see any nuxt build occurring.

**Comment by uptownhr** [comment]
so for me is because `yarn` for some odd reason resolved alpha.4 to alpha2. I used `npm install` instead and fixed the problem.

**Comment by Kitchu0401** [comment]
@uptownhr 
Thx, using `npm install` worked for me!

Plus, first I was in state with of installation completed with `yarn`, and calling `npm install` didn't help.
I removed whole project directory and re-init project, and finally it works! 😄
