### ISSUE TITLE
How to debug with node-inspector

### ISSUE THREAD

**Issue by jyanchen** [nuxt-community/express-template#52]
I want to debug node server side code, I have tried add '--debug' or '--inspect' or node-inspector, no matter which way still can not debug node server side code. Please tell me how to go it

**Comment by vuchl** [comment]
when you run `npm run dev` the server side errors are reported to the terminal window:

![2017-06-28 13_28_51-clipboard](https://user-images.githubusercontent.com/4921147/27635018-d997de42-5c05-11e7-8044-b02d7e1fd1a4.png)

**Comment by Gi60s** [comment]
Server side debugging is not the same thing as seeing console messages. I would also like to see this feature working: https://nodejs.org/dist/latest-v8.x/docs/api/debugger.html#debugger_v8_inspector_integration_for_node_js
