### ISSUE TITLE
Error with Node 8

### ISSUE THREAD

**Issue by ald890** [nuxt-community/express-template#54]
I have Node v8.1.2, after running `npm run dev`

Error:
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: app.use() requires middleware functions`

The problem is here: `app.use(nuxt.render)`
With Node 7.* is working properly.

**Comment by haffla** [comment]
I've got the exact same problem but sadly I'm on Node v7.1.0.

**Comment by wanoo21** [comment]
Thanks!

**Comment by ald890** [comment]
To fix this problem please upgrade npm to 5.3
`npm install npm@latest -g`
