### ISSUE TITLE
How to start for PM2?

### ISSUE THREAD

**Issue by ydwan** [nuxt-community/express-template#56]
How to start for PM2?

**Comment by ydwan** [comment]
how to start this project for PM2

**Comment by ald890** [comment]
`cross-env NODE_ENV=production pm2 start build/main.js`

You can put this into package.json

`"scripts": {
  `  "start_pm": "cross-env NODE_ENV=production pm2 start build/main.js",`
 ` },`

**Comment by ydwan** [comment]
thanks!:)
