### ISSUE TITLE
How to start with passportjs ?

### ISSUE THREAD

**Issue by binler** [nuxt-community/express-template#57]
I build a login with github?
Code:
index.js
`import Nuxt from 'nuxt'
import express from 'express'
var session = require('express-session');
var passport = require('passport');
var GitHubStrategy = require('passport-github2').Strategy;
require('dotenv').config()

var GITHUB_CLIENT_ID = "d31b61d6f66614bae0cf";
var GITHUB_CLIENT_SECRET = "7fbd3cd8ee9b9f367d05488c8d83838b675a7532";

import api from './api'

const app = express()
const host = process.env.HOST || '127.0.0.1'
const port = process.env.PORT || 3000

passport.serializeUser(function(user, done) {
  done(null, user);
});

passport.deserializeUser(function(obj, done) {
  done(null, obj);
});

app.set('port', port)

// Import API Routes
app.use('/api', api)

passport.use(new GitHubStrategy({
    clientID: GITHUB_CLIENT_ID,
    clientSecret: GITHUB_CLIENT_SECRET,
    callbackURL: "http://localhost:8080/api/auth/github/callback"
  },
  function(accessToken, refreshToken, profile, done) {
    // asynchronous verification, for effect...
    process.nextTick(function () {
      return done(null, profile);
    });
  }
));
app.use(session({ secret: 'keyboard cat', resave: true, saveUninitialized: true }));
app.use(passport.initialize())
app.use(passport.session())

// Start nuxt.js
async function start() {
  // Import and Set Nuxt.js options
  let config = require('../nuxt.config.js')
  config.dev = !(process.env.NODE_ENV === 'production')
  // Instanciate nuxt.js
  const nuxt = new Nuxt(config)
  // Add nuxt.js middleware
  app.use(nuxt.render)
  // Listen the server
  app.listen(port, host)
  console.log('Server listening on ' + host + ':' + port) // eslint-disable-line no-console
}

start()
`

auth.js

`import { Router } from 'express'
var passport = require('passport');
var router = Router()

router.get('/auth/github', passport.authenticate('github', { scope: [ 'user:email' ] }));

router.get('/auth/github/callback', passport.authenticate('github', { failureRedirect: '/' }),
  function(req, res) {
    // Successful authentication, redirect home.
    res.redirect('/');
  });

export default router
`

but router.get('/auth/github/callback' not working. please help me!!!!

**Comment by derekshull** [comment]
I have a starter kit for Nuxt that includes PassportJS using JSON Web Tokens.  https://github.com/derekshull/nuxt-starter-kit

Hope it helps!

**Comment by iamdubx** [comment]
@derekshull  your example is not working.
```
Error: 

Vue packages version mismatch:

- vue@2.4.2
- vue-server-renderer@2.3.4
```

**Comment by derekshull** [comment]
@iamdubx this has been fixed now! https://github.com/derekshull/nuxt-starter-kit/issues/1

**Comment by iamdubx** [comment]
@derekshull thank you, very handy example.

**Comment by wwb568109135** [comment]
https://github.com/derekshull/nuxt-starter-kit/blob/7d55b84afa9ab553cbe06a96855557c639c186b4/server/index.js
