### ISSUE TITLE
npm run dev doesn't work

### ISSUE THREAD

**Issue by Harry97** [nuxt-community/express-template#59]
After cloning the template using vue-cli and running npm install, I ran into this error (check the included picture). So, I deleted the folder and redid the whole thing, but used yarn instead, and I'm still getting the same error!
![screenshot from 2017-07-10 19-35-43](https://user-images.githubusercontent.com/6644545/28064698-f531bdd2-6635-11e7-827f-552bdcf04bf8.png)

**Comment by anguer** [comment]
![image](https://user-images.githubusercontent.com/16484472/28709794-39e6d03a-73b4-11e7-9578-7109142ddf30.png)

遇到相同问题

**Comment by Harry97** [comment]
Glad I'm not the only one running into this problem, hopefully someone can help us out.

**Comment by Atinux** [comment]
It should be fix now :)

Can you try to install it again with `vue-cli` and re-open if you still have an error?

**Comment by Harry97** [comment]
@Atinux I hate to be a buzz killer but the problem still persists.
![nuxt](https://user-images.githubusercontent.com/6644545/29002024-20e716f8-7a99-11e7-8e70-ca5410e6f3aa.png)
