### ISSUE TITLE
https on localhost

### ISSUE THREAD

**Issue by itsMattShull** [nuxt-community/express-template#60]
I've done this in other node projects before.  New to Nuxt but thought it'd be similar.

```
import Nuxt from 'nuxt'
import express from 'express'

import api from './api'

const app = express();
const host = process.env.HOST || 'localhost';
const port = process.env.PORT || 3000;
const https = require("https");
const fs = require("fs");
const serverConfig = require('./config.json')[process.env.NODE_ENV || 'development'];

const pkey = fs.readFileSync(serverConfig.HTTPS_KEY);
const pcert = fs.readFileSync(serverConfig.HTTPS_CERT);
const httpsOptions = {
    key: pkey,
    cert: pcert
};

app.set('port', port);

// Import API Routes
app.use('/api/v1', api);

// Start nuxt.js
async function start() {
  // Import and Set Nuxt.js options
  let config = require('../nuxt.config.js')
  config.dev = !(process.env.NODE_ENV === 'production')
  // Instanciate nuxt.js
  const nuxt = new Nuxt(config)
  // Add nuxt.js middleware
  app.use(nuxt.render)
  // Listen the server
  https.createServer(httpsOptions, app).listen(port, host);
  console.log('Server listening on ' + host + ':' + port) // eslint-disable-line no-console
}

start()
```

When I run this the /api/v1/users endpoint and all other API endpoints work, but when I go to https://localhost:3000 it gives me: 

```
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Been digging around for a couple of days but no luck.  Anyone have a clue to get me started down the right path?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c43">#c43</a>)</em></sub></div>

**Comment by derekshull** [comment]
After much head banging I'm not scratching my head.  I found a solution but have no idea why it works...because I feel like it shouldn't...

If I replace `https.createServer(httpsOptions, app).listen(port, host);` with:
```
  app.listen(port, host);
  https.createServer(httpsOptions, app).listen(3001, "localhost");
```

It works.  I also get http://locahost:3000 too.  Very odd.  Anyone have an explanation?  Can I get it to work without `app.listen(port, host);`?

**Comment by derekshull** [comment]
More info.  It appears asyncData() in index.vue is what causes this to happen.  Took it out and it worked fine.  Still digging.  More to come.

**Comment by xloading** [comment]
@derekshull did you fix this somehow?
I'm facing the same issue with Nuxt, but on pure Node without Express
https://github.com/nuxt/nuxt.js/issues/3463

**Comment by derekshull** [comment]
@xloading apparently the bot didn't like my formatting and closed it as a question but it's still unresolved here on the community forum: https://cmty.app/nuxt/express-template/issues/c99
