### ISSUE TITLE
about ssr-cookie

### ISSUE THREAD

**Issue by jimliang** [nuxt-community/express-template#63]
```
export default function({isServer, req}) {
  if (isServer) {
    axios.defaults.headers.common.cookie = req.headers.cookie
  }
}
```

I see ssr-cookie.js, It set the global cookie from req.

How to ensure each req context use the same cookie?

**Comment by Atinux** [comment]
Hi @jimliang 

Please take a look at [axios module](https://github.com/nuxt-community/modules/tree/master/modules/axios) to see how it works with credentials.
