### ISSUE TITLE
Currently failing for the latest version of Nuxt.js ?

### ISSUE THREAD

**Issue by piyushchauhan2011** [nuxt-community/express-template#65]
Hi @pi0 , I recently upgraded Nuxt.js to latest release which is `rc2`. For some reason, the `run dev` and `build` is failing with this template ? I was hoping if there's a quick solution to resolve problem apart from downgrading the `nuxt` version ? 

**Error:**

```
(node:4906) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_2_nuxt___default.a is not a constructor
```

**Comment by kevincpan** [comment]
I am having the same issue, currently downgrading to 1.0.0-alpha.5 as a workaround, but would like to know the correct fix for this :).

**Comment by Prozi** [comment]
I downgraded to 1.0.0-alpha.5
There are multiple unexplained changes in rc1/rc2
Like
`import { Nuxt, Builder, Renderer } from 'nuxt'`
is a necessary change in template
There are more but I haven't got it working yet after an hour I downgraded just as @kevincpan

**Comment by piyushchauhan2011** [comment]
Hey mate, Thanks for confirming. Looking forward for Changelog, a bit pain to understand what's changed. Keep me updated for any @Prozi 
Chaow!

**Comment by Atinux** [comment]
It's now working with `rc3` :)

**Comment by piyushchauhan2011** [comment]
Cheers @Atinux 💯

**Comment by Prozi** [comment]
Confirmed it works, you can close this.
Thanks @Atinux
