### ISSUE TITLE
Deploy with Zeit's 'now' shows ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by plakak** [nuxt-community/express-template#67]
After deploying template with Zeit's `now` (empty project generated with `vue init nuxt-community/express`) I can access `/api` route but the site itself returns `ERR_SPDY_PROTOCOL_ERROR`

This works: https://test-vvyxsxcicp.now.sh/api/users
This doesn't: https://test-vvyxsxcicp.now.sh/ 

Might be related to #60 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c49">#c49</a>)</em></sub></div>

**Comment by chardy** [comment]
I am having the same issue. Anyone has the same issue? Can help to solve this?
