### ISSUE TITLE
What is {{{{raw}}}}... {{{{/raw}}}} for?

### ISSUE THREAD

**Issue by lautiamkok** [nuxt-community/express-template#69]
What is` {{{{raw}}}}... {{{{/raw}}}}` for?

e.g. from https://github.com/nuxt-community/koa-template/blob/master/template/layouts/error.vue

```
{{{{raw}}}}
<template>
  <section class="container">
    <img src="../assets/img/logo.png" alt="Nuxt.js Logo" />
    <h1 class="title">
      {{ error.statusCode }}
    </h1>
    <h2 class="info">
      {{ error.message }}
    </h2>
    <nuxt-link class="button" to="/" v-if="error.statusCode === 404">
      Homepage
    </nuxt-link>
  </section>
</template>
{{{{/raw}}}}
```
Can't find anything about it from the doc - https://nuxtjs.org/guide/views

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c51">#c51</a>)</em></sub></div>

**Comment by alanaasmaa** [comment]
Same question.

**Comment by o8e** [comment]
I am also curious.

**Comment by microcipcip** [comment]
I think these are just placeholders used by Vue cli when you install for the first time, in fact they are removed after installation.

**Comment by alanaasmaa** [comment]
They were not removed for me but that makes sense what they are.

**Comment by microcipcip** [comment]
Maybe you installed the project downloading it from Github directly, not installing it with the Vue cli?

**Comment by andrewbiang888** [comment]
I have the same question. Does it prep the component for an axios/ajax request to prompt it for dynamic content? Seems like it has a useful application and would love to learn about it! I will comment if I figure it out.

**Comment by lautiamkok** [comment]
@andrewbiang888 I think that might be the old syntax. Just ignore it when you use the latest version. Should give it a go. It is a great framework!

**Comment by lautiamkok** [comment]
For those who are interested using Nuxt with Express, you can take a look how I use them https://github.com/lautiamkok/nuxt-express
