### ISSUE TITLE
如果用pm2，怎么启动？

### ISSUE THREAD

**Issue by liujianping520** [nuxt-community/express-template#70]
如果用pm2，怎么启动？

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c52">#c52</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
我很抱歉，我不会说中文

1. Build your project:
`npm build`

2. Start your project
`pm2 start npm --name "your-project-alias" -- start`

3. Check the status: 
`pm2 status`

4. Restart:
`pm2 restart your-project-alias`

5. Stop:
`pm2 stop your-project-alias`

**Comment by liujianping520** [comment]
Thank you!
