### ISSUE TITLE
Build time

### ISSUE THREAD

**Issue by arashsa** [nuxt-community/express-template#74]
I am experiencing around 5 seconds build time after initial installation. I don't know if this is an issue, or the build time is actually that long.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c57">#c57</a>)</em></sub></div>

**Comment by gangsthub** [comment]
Same here. Updating the front part is fast. But if you "compile" the backend part, it takes some time (5-10 secs). I've run it thorugh `npm run dev`.

**Comment by microcipcip** [comment]
Same here, I haven't ever used backpack, maybe that is slowing down the server?

**Comment by nekdolan** [comment]
Hi guys. I've made a fork that uses a proxy for the api server in dev mode. It speeds up build time and allows nuxt to use hot reloading consistently. You can check it here: https://github.com/nekdolan/express-template-hot .

**Comment by microcipcip** [comment]
Yeah, that's what I ended up doing as well, thanks for sharing :)
