### ISSUE TITLE
Cannot find module '@nuxtjs/youch'

### ISSUE THREAD

**Issue by liujianping520** [nuxt-community/express-template#75]
Cannot find module '@nuxtjs/youch'

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c56">#c56</a>)</em></sub></div>

**Comment by gangsthub** [comment]
The error reporter missing is kinda  funny haha. Try making a `npm install` again and look for any `ERR`or message. There's not much info to give you enough feedback.

What version of `npm` do you have?

`@nuxtjs/youch` is a nuxt dependency. You should not install it manually.

**Comment by gangsthub** [comment]
@gsotelo10 what is the error log? Upgrading to the latest version is not recommendable right now. Node@10.0.0 is not to be used in production as of today.

**Comment by gsotelo10** [comment]
Hi @gangsthub 

I'm trying to install nuxt after created (vue init nuxt-community/starter-template) my nameproyect, then I put the command "npm install" and the error is 

npm ERR! code E404
npm ERR! 404 Not Found: @nuxtjs/youch@^4.2.3

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gerardo\AppData\Roaming\npm-cache\_logs\2018-04-30T19_00_55_892Z-debug.log

I have node v8.11.1 and npm 6.0.0 

I tried to install in friend's laptop(hp win 8.1) and was successful but not in my laptop (dell inspiron Win 8.1)

How can I ommit youch on command line ??

**Comment by gangsthub** [comment]
I think youch may not be the problem (and omission is not an option). If you make a fresh install and everything works as expected, you may have a typo or an unexpected change in your **package.json**.

This is the original one:
https://github.com/nuxt-community/starter-template/blob/master/template/package.json

Or a problem with `npm`. Does your friend have `npm@5.6.0`? (`npm -v` to check it out) Is the one that comes by default with `v8.11.1` (node versions and npm versions are more important in this case than Windows versions; IMO): [Reference](https://nodejs.org/en/download/releases/)

I insist in checking npm, installing (npm i -g npm@5.6.0) and reinstalling in the project folder with default `npm install`

**Comment by gsotelo10** [comment]
Actually I have the same package.json. 

With npm I had it before and it didn't work, then I upgrade npm to 6.0.0 and node v8.11.1
look...

![error en nuxtjs.JPG](https://cmty.s3.eu-west-1.amazonaws.com/79895193/93d9f0e0-4cb7-11e8-9f15-5f8b630f3d03.JPG)

On my Friend's laptop I installed for the first time nodejs npm and vue-cli then nuxt and it worked.

 I don't know whats wrong couse I have installed several projects in different folders and it doesn't work.

I have others proyects with vuejs and works good.  Do I should back to npm @5.6.0 ?

**Comment by gangsthub** [comment]
It seems to me that the problem may have to be more with the npm version, yes. The default node@8.11.1 + npm@5.6.0 should work. Try deleting the npm cache also... `npm cache clean --force` (as last option).

**Comment by gsotelo10** [comment]
I'm gonna kill myself jaja 

I did what we said and still not working... 

Mmm any other recommendation similar to nuxt that works good with vuejs ?

**Comment by gangsthub** [comment]
Sorry to hear that it's not working for you. BTW, this is the issue tracker for express-template, not starter-template. That confused me a little.

I cannot reproduce neither with starter-template nor express-template.

Please, add the debug log that appears on the error message as a gist: http://gist.github.com I can keep on trying to help you.

Another possible cause could be that _you're on a network connection via a proxy_ (https://github.com/npm/npm/issues/4072#issuecomment-27579430). Or not having the npm registry correctly configured. If running `npm config get registry` gives you something different from `https://registry.npmjs.org`, `npm config set registry https://registry.npmjs.org` would do it.

>  similar to nuxt

I don't know something similar to Nuxt using Vue. At least as powerful.

**Comment by gsotelo10** [comment]
I appreciate it !

Heres is the log https://gist.github.com/gsotelo10/4374749c59d17ea1e9fb1748c038aea2


(- you're on a network connection via a proxy) 

mmm I don´t know because the network was the same when I tried with another laptop.
Or maybe, could be the  antivirus program that blocks the installation. I'm using Avira 

If is that I'll uninstall Avira program

**Comment by gangsthub** [comment]
Yes, my guess is that something is blocking your connection. May be the AV. I can access the URLs that return 404s for you. For example: https://registry.npmjs.org/@nuxtjs%2fyouch (via raw http).

If you can see that in your browser, maybe node is the one being blocked. But the AV is the #1 culprit in my opinion.

**Comment by gsotelo10** [comment]
Nop I uninstall AV and still the same error I restarted the pc and created a new vue init nuxt but still get the error... 

![packagejson and error.JPG](https://cmty.s3.eu-west-1.amazonaws.com/79895193/8b6fcb90-4d67-11e8-9726-fd334d53a398.JPG)

**Comment by gsotelo10** [comment]
Nop, I uninstall all AV components, I restarted my pc and created another vue init nuxt and still get the error...

I'm trying with hyper console and vs code console.


![packagejson and error.JPG](https://cmty.s3.eu-west-1.amazonaws.com/79895193/274f5c10-4d68-11e8-ac8e-8510ad718bff.JPG)

**Comment by gangsthub** [comment]
Did you do exactly `vue init nuxt-community/starter-template pnuxt`?

**Comment by gsotelo10** [comment]
Yes !!

**Comment by gangsthub** [comment]
Can you access `https://registry.npmjs.org/@nuxtjs%2fyouch` in your browser?

**Comment by gsotelo10** [comment]
I created a Virtual Machin with Ubuntu... it works ! thanks a lot !
