### ISSUE TITLE
Build failed after using backpack.

### ISSUE THREAD

**Issue by wushan** [nuxt-community/express-template#79]
I was able to use express without any problems before, but facing this issue after using the new express-template which uses backpack-core.

does anybody has the similar issue here ?
I was using these commands

npm build: `nuxt build`  -> `"build": "nuxt build && backpack build"`
npm start: `NODE_ENV=production node ./server.js`, with backpack, now the command is `cross-env NODE_ENV=production node build/main.js`

although the error message shows the problem is occurring at the command `"build": "nuxt build && backpack build"`, but if I run the command `npm run build`, it builds without any error. So I think we can narrow down the issue in the `start` script.

```
sh: 1: backpack: not found
npm info lifecycle jdb-history-tracer@1.0.0~build: Failed to exec build script
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! jdb-history-tracer@1.0.0 build: `nuxt build && backpack build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the jdb-history-tracer@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-01T10_50_06_061Z-debug.log
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c62">#c62</a>)</em></sub></div>

**Comment by wushan** [comment]
update:
I've tested the `npm run start` script with `"start": "NODE_ENV=production node build/main.js"`  and its runs successful.

but the problem still happens when building a docker image.
following is the dockerfile settings.
```
FROM node:8.2.1

ENV NODE_ENV=production
ENV HOST 0.0.0.0

RUN mkdir -p /app
COPY . /app
WORKDIR /app
# Expose the app port
EXPOSE 3000

RUN npm install
RUN npm run build
CMD ["npm", "start"]
```

**Comment by wushan** [comment]
Update:
I can now run the project properly after getting rid of backpack and slightly change the import part of server.js

server.js
```
// import { Nuxt, Builder } from 'nuxt'
const {Nuxt} = require('nuxt')
const {Builder} = require('nuxt')
```

package.json
```
"scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "NODE_ENV=production node ./server.js"
}
```

**Comment by Prozi** [comment]
change first 3 lines to const { Nuxt, Builder } = require('nuxt')

and backpack not found is because of no npm install backpack --save ?

**Comment by wushan** [comment]
@Prozi I could confirm that backpack-core is in package.json dependency, and It rans smoothly on local `npm run build && npm run start`, the issue comes only when building in a docker container.
