### ISSUE TITLE
module error after vue init nuxt-community/express-template <project-name>

### ISSUE THREAD

**Issue by fidellr** [nuxt-community/express-template#81]
today i started to check the nuxt express template, then i decided to test it and got an error after running the localhost with `npm run dev` or `yarn run dev`, and this the error:
module.js:491
    throw err;
    ^

Error: Cannot find module 'D:\path\to\nuxtExpress\testProject\"D:\pa'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3

forgive me if its because of my fault tht caused this error, but i don't see i'm doing wrong with it because i'm not even edit it yet after installing all the dependencies with `yarn install`, i hope it will be fix soon thanks in advance

**Comment by vaggelis2018** [comment]
@fidellr how you fixed this issue?
