### ISSUE TITLE
how to  use postsss in express-template 

### ISSUE THREAD

**Issue by shadow198** [nuxt-community/express-template#82]
i want use postcss with webpack, but webpack.config.js file  is not found  in project,what should i do?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c63">#c63</a>)</em></sub></div>

**Comment by corygibbons** [comment]
@shadow198 Try this: https://nuxtjs.org/faq/postcss-plugins/
