### ISSUE TITLE
IE9 issue with router mode 'hash'

### ISSUE THREAD

**Issue by poloop** [nuxt-community/express-template#86]
When I test my app on IE9 with fallback set to 'hash', I got the following error when I'm trying to refresh any page except landing one, or If I'm trying access a specific page :

**[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.** 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c67">#c67</a>)</em></sub></div>

**Comment by tian-tian** [comment]
I have the same problem, anyone know how to solve the problem？

**Comment by JasonGaoG** [comment]
me too, anyone know why?
