### ISSUE TITLE
vuex doesn't work

### ISSUE THREAD

**Issue by worstprogrammerCN** [nuxt-community/express-template#87]
The template doesn't have a 'store' folder in it, so I created one and put an 'index.js' in the folder.
But when I reference to 'this.$store' in '.vue' file, it warns 'it is undefined'.
It seems that the vuex doesn't make an effect?
How to make use of vuex in this template?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c68">#c68</a>)</em></sub></div>

**Comment by five6** [comment]
I got the same problem ！

**Comment by paulgv** [comment]
What does your code look like in `~/store/index.js`?

**Comment by cmh1996** [comment]
I want to ask that if the problem is solved?

**Comment by Drezdenozk** [comment]
same problem here... code in index.js copy-pasted from nuxt site "store" tutorial

**Comment by chandler0415** [comment]
nobody to fix it?

**Comment by BingxingXu** [comment]
Try this code
```js
// project_root_path/store/index.js
export const state = () => {
  return {
    name: 'foo'
  }
}
```
```html
// in vue file
<template>
...
   {{$store.state.name}}
...
</template>
```

**Comment by lanbau** [comment]
This works for me

~/store/index.js

`import Vuex from 'vuex'

const createStore = () => {
  return new Vuex.Store({
    state: {
      counter: 0
    },
    mutations: {
      increment (state) {
        state.counter++
      }
    }
  })
}

export default createStore
`

**Comment by wtilton** [comment]
Having the same issue. I just created a new nuxt application. I tried using both @BingxingXu state function and then @lanbau createStore. Both result in this.$store == undefined. I'll try creating another nuxt app to see if that fixes it. Bummer there wasn't a solution to this. :(

**Comment by dminchev** [comment]
Try creating a file in `root/stores/index.js` and add the following content 

```javascript
export default {
  state: () => ({})
}

```
