### ISSUE TITLE
How to disable minification for html and css

### ISSUE THREAD

**Issue by vkatsar** [nuxt-community/express-template#93]
Hello everybody.

I am trying to disable minification for html and css with no success. I tried to use the generate - minify option from the nuxt documentation but nothing happened.

Can anybody help ?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c73">#c73</a>)</em></sub></div>

**Comment by josteph** [comment]
**nuxt.config.js**

```
    html: {
      minify: {
        collapseWhitespace: false,
        collapseBooleanAttributes: true,
        decodeEntities: true,
        minifyCSS: false, // this
        minifyJS: false, // this
        processConditionalComments: true,
        removeEmptyAttributes: true,
        removeRedundantAttributes: true,
        trimCustomFragments: true,
        useShortDoctype: true
      }
    },
```
