### ISSUE TITLE
Auth session doesn't work

### ISSUE THREAD

**Issue by lukasamd** [nuxt-community/express-template#94]
Hello,
I use this template and also auth using this guide:
https://nuxtjs.org/examples/auth-routes

There is also passport on server side, but I think it doesn't matter. 
Authorization works fine but session is not kept and after page reloading, user must login again.

What can be wrong?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c74">#c74</a>)</em></sub></div>

**Comment by gamelaster** [comment]
Probably it's something related to `nuxtServerInit`, since there you commit your user information to store. Check if in `nuxtServerInit` you have commiting the right data

**Comment by sunyongK** [comment]
same ploblem....

**Comment by danangtamtomo** [comment]
Is there any update for this problem?
