### ISSUE TITLE
Live 

### ISSUE THREAD

**Issue by AliakbarSu** [nuxt-community/express-template#95]
Live Demo is giving 500 error

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c75">#c75</a>)</em></sub></div>

**Comment by aral** [comment]
Now a 502

**Comment by DylanC** [comment]
Still a 502 error.

**Comment by josteph** [comment]
Now 404.
