### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by pedramk** [nuxt-community/express-template#96]
Could you please update this template to latest nuxt?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c76">#c76</a>)</em></sub></div>

**Comment by christophwolff** [comment]
would be great!

**Comment by Chaciej** [comment]
Agreed, to this day this one is the best, most viable template for me (ES6 imports working on server side)
